version: '3'
services:
  react-tasks:
    build: ./web/tasks
    ports:
      - "3000:3000"

  db:
    build: ./database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "12345"
      MYSQL_USER: "facu"
      MYSQL_DATABASE: "DOCKER_TODO_LIST"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  go-tasks:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql_data:
