CREATE DATABASE DOCKER_TODO_LIST;
USE DOCKER_TODO_LIST;

DELIMITER //
CREATE PROCEDURE CreateTask(IN description VARCHAR(255))
BEGIN
	INSERT INTO Task (description) VALUES (description);
END //
DELIMITER ;